<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1pccNWZ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1pccNWZ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1pccNWZ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1pccNWZ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container1pccNWZ\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '1pccNWZ',
    'container.build_id' => 'd05873ca',
    'container.build_time' => 1646907048,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1pccNWZ');
